//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace faderPlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("faderPlugin.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        internal static string AboutIssues {
            get {
                return ResourceManager.GetString("AboutIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ko-Fi Tip.
        /// </summary>
        internal static string AboutKoFi {
            get {
                return ResourceManager.GetString("AboutKoFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Thread.
        /// </summary>
        internal static string AboutThread {
            get {
                return ResourceManager.GetString("AboutThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fader plugin disabled..
        /// </summary>
        internal static string ChatPluginDisabled {
            get {
                return ResourceManager.GetString("ChatPluginDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fader plugin enabled..
        /// </summary>
        internal static string ChatPluginEnabled {
            get {
                return ResourceManager.GetString("ChatPluginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance List 1.
        /// </summary>
        internal static string ElementAllianceList1 {
            get {
                return ResourceManager.GetString("ElementAllianceList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance List 2.
        /// </summary>
        internal static string ElementAllianceList2 {
            get {
                return ResourceManager.GetString("ElementAllianceList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bozja Hud.
        /// </summary>
        internal static string ElementBozjaHud {
            get {
                return ResourceManager.GetString("ElementBozjaHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast Bar.
        /// </summary>
        internal static string ElementCastbar {
            get {
                return ResourceManager.GetString("ElementCastbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ElementChat {
            get {
                return ResourceManager.GetString("ElementChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Action Hotbar.
        /// </summary>
        internal static string ElementContextActionHotbar {
            get {
                return ResourceManager.GetString("ElementContextActionHotbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmic Exploration Info.
        /// </summary>
        internal static string ElementCosmicAnnouncements {
            get {
                return ResourceManager.GetString("ElementCosmicAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmic Exotablet.
        /// </summary>
        internal static string ElementCosmicExotablet {
            get {
                return ResourceManager.GetString("ElementCosmicExotablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Hotbar.
        /// </summary>
        internal static string ElementCrossHotbar {
            get {
                return ResourceManager.GetString("ElementCrossHotbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string ElementCurrency {
            get {
                return ResourceManager.GetString("ElementCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty List.
        /// </summary>
        internal static string ElementDutyList {
            get {
                return ResourceManager.GetString("ElementDutyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eureka Elemental Wheel.
        /// </summary>
        internal static string ElementEurekaElementalHud {
            get {
                return ResourceManager.GetString("ElementEurekaElementalHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eureka Logos Actions.
        /// </summary>
        internal static string ElementEurekaLogosHud {
            get {
                return ResourceManager.GetString("ElementEurekaLogosHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Bar.
        /// </summary>
        internal static string ElementExperienceBar {
            get {
                return ResourceManager.GetString("ElementExperienceBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar 1.
        /// </summary>
        internal static string ElementHotbar1 {
            get {
                return ResourceManager.GetString("ElementHotbar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar 10.
        /// </summary>
        internal static string ElementHotbar10 {
            get {
                return ResourceManager.GetString("ElementHotbar10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar 2.
        /// </summary>
        internal static string ElementHotbar2 {
            get {
                return ResourceManager.GetString("ElementHotbar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar 3.
        /// </summary>
        internal static string ElementHotbar3 {
            get {
                return ResourceManager.GetString("ElementHotbar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar 4.
        /// </summary>
        internal static string ElementHotbar4 {
            get {
                return ResourceManager.GetString("ElementHotbar4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar 5.
        /// </summary>
        internal static string ElementHotbar5 {
            get {
                return ResourceManager.GetString("ElementHotbar5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar 6.
        /// </summary>
        internal static string ElementHotbar6 {
            get {
                return ResourceManager.GetString("ElementHotbar6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar 7.
        /// </summary>
        internal static string ElementHotbar7 {
            get {
                return ResourceManager.GetString("ElementHotbar7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar 8.
        /// </summary>
        internal static string ElementHotbar8 {
            get {
                return ResourceManager.GetString("ElementHotbar8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotbar 9.
        /// </summary>
        internal static string ElementHotbar9 {
            get {
                return ResourceManager.GetString("ElementHotbar9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Grid.
        /// </summary>
        internal static string ElementInventoryGrid {
            get {
                return ResourceManager.GetString("ElementInventoryGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islekeep&apos;s Index.
        /// </summary>
        internal static string ElementIslekeepIndex {
            get {
                return ResourceManager.GetString("ElementIslekeepIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string ElementJob {
            get {
                return ResourceManager.GetString("ElementJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Break.
        /// </summary>
        internal static string ElementLimitBreak {
            get {
                return ResourceManager.GetString("ElementLimitBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string ElementMainMenu {
            get {
                return ResourceManager.GetString("ElementMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimap.
        /// </summary>
        internal static string ElementMinimap {
            get {
                return ResourceManager.GetString("ElementMinimap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplates.
        /// </summary>
        internal static string ElementNameplate {
            get {
                return ResourceManager.GetString("ElementNameplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occult Crescent Hud.
        /// </summary>
        internal static string ElementOccultCrescentHud {
            get {
                return ResourceManager.GetString("ElementOccultCrescentHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string ElementParameters {
            get {
                return ResourceManager.GetString("ElementParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party List.
        /// </summary>
        internal static string ElementPartyList {
            get {
                return ResourceManager.GetString("ElementPartyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Hotbar.
        /// </summary>
        internal static string ElementPetHotbar {
            get {
                return ResourceManager.GetString("ElementPetHotbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestLog.
        /// </summary>
        internal static string ElementQuestLog {
            get {
                return ResourceManager.GetString("ElementQuestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Guide.
        /// </summary>
        internal static string ElementScenarioGuide {
            get {
                return ResourceManager.GetString("ElementScenarioGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Information.
        /// </summary>
        internal static string ElementServerInformation {
            get {
                return ResourceManager.GetString("ElementServerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ElementStatus {
            get {
                return ResourceManager.GetString("ElementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Conditional.
        /// </summary>
        internal static string ElementStatusConditional {
            get {
                return ResourceManager.GetString("ElementStatusConditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Enfeeblements.
        /// </summary>
        internal static string ElementStatusEnfeeblements {
            get {
                return ResourceManager.GetString("ElementStatusEnfeeblements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Enhancements.
        /// </summary>
        internal static string ElementStatusEnhancements {
            get {
                return ResourceManager.GetString("ElementStatusEnhancements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Other.
        /// </summary>
        internal static string ElementStatusOther {
            get {
                return ResourceManager.GetString("ElementStatusOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Info.
        /// </summary>
        internal static string ElementTargetInfo {
            get {
                return ResourceManager.GetString("ElementTargetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Actions (for example in Island, Criterion or certain fights).
        /// </summary>
        internal static string ElementTooltipActionHotbar {
            get {
                return ResourceManager.GetString("ElementTooltipActionHotbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be always visible if focused, albeit feature can be buggy with some configurations.
        /// </summary>
        internal static string ElementTooltipChat {
            get {
                return ResourceManager.GetString("ElementTooltipChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WXHB is always visible, unless the option &apos;Position WXHB separately from XHB&apos; is used.
        /// </summary>
        internal static string ElementTooltipCrosshotbar {
            get {
                return ResourceManager.GetString("ElementTooltipCrosshotbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job-specific UI.
        /// </summary>
        internal static string ElementTooltipJob {
            get {
                return ResourceManager.GetString("ElementTooltipJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet and mount actions.
        /// </summary>
        internal static string ElementTooltipPetHotbar {
            get {
                return ResourceManager.GetString("ElementTooltipPetHotbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player status (when not split into 3 separate elements).
        /// </summary>
        internal static string ElementTooltipStatus {
            get {
                return ResourceManager.GetString("ElementTooltipStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player conditional status (when split into 4 separate elements).
        /// </summary>
        internal static string ElementTooltipStatusConditional {
            get {
                return ResourceManager.GetString("ElementTooltipStatusConditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player enfeeblements (when split into 3 separate elements).
        /// </summary>
        internal static string ElementTooltipStatusEnfeeblements {
            get {
                return ResourceManager.GetString("ElementTooltipStatusEnfeeblements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player enhancements (when split into 3 separate elements).
        /// </summary>
        internal static string ElementTooltipStatusEnhancements {
            get {
                return ResourceManager.GetString("ElementTooltipStatusEnhancements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player other status (when split into 3 separate elements).
        /// </summary>
        internal static string ElementTooltipStatusOther {
            get {
                return ResourceManager.GetString("ElementTooltipStatusOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string ElementUnknown {
            get {
                return ResourceManager.GetString("ElementUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string HoverGroupNewGroup {
            get {
                return ResourceManager.GetString("HoverGroupNewGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rule Groups.
        /// </summary>
        internal static string RuleGroupsHeader {
            get {
                return ResourceManager.GetString("RuleGroupsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        internal static string RuleElementsHeader {
            get {
                return ResourceManager.GetString("RuleElementsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string RuleGroupName {
            get {
                return ResourceManager.GetString("RuleGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Rules.
        /// </summary>
        internal static string RuleGroupConfiguration {
            get {
                return ResourceManager.GetString("RuleGroupConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Linked Hover.
        /// </summary>
        internal static string RuleGroupLinkHover {
            get {
                return ResourceManager.GetString("RuleGroupLinkHover", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hovering any member activates Hover for every member addon in this group..
        /// </summary>
        internal static string RuleGroupLinkHoverTooltip {
            get {
                return ResourceManager.GetString("RuleGroupLinkHoverTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shared Rules.
        /// </summary>
        internal static string RuleGroupSharedRules {
            get {
                return ResourceManager.GetString("RuleGroupSharedRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Members use this group&apos;s conditions, opacity, disabled state, and fade settings instead of their own saved rules..
        /// </summary>
        internal static string RuleGroupSharedRulesTooltip {
            get {
                return ResourceManager.GetString("RuleGroupSharedRulesTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is using shared rules from {1}..
        /// </summary>
        internal static string RuleGroupInherited {
            get {
                return ResourceManager.GetString("RuleGroupInherited", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element&apos;s own rules are preserved and will be used again after it leaves the shared rules group..
        /// </summary>
        internal static string RuleGroupIndependentRulesPreserved {
            get {
                return ResourceManager.GetString("RuleGroupIndependentRulesPreserved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        internal static string RuleGroupEditGroup {
            get {
                return ResourceManager.GetString("RuleGroupEditGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detach and Keep Current Rules.
        /// </summary>
        internal static string RuleGroupDetachKeepRules {
            get {
                return ResourceManager.GetString("RuleGroupDetachKeepRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        internal static string HoverGroupsAddGroup {
            get {
                return ResourceManager.GetString("HoverGroupsAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements in Group.
        /// </summary>
        internal static string HoverGroupsElements {
            get {
                return ResourceManager.GetString("HoverGroupsElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a group to edit its details..
        /// </summary>
        internal static string HoverGroupsHint {
            get {
                return ResourceManager.GetString("HoverGroupsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing group from the left or click &apos;Add Group&apos; to create a new one..
        /// </summary>
        internal static string HoverGroupsTutorialBody1 {
            get {
                return ResourceManager.GetString("HoverGroupsTutorialBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign UI elements to the group using the checkboxes..
        /// </summary>
        internal static string HoverGroupsTutorialBody2 {
            get {
                return ResourceManager.GetString("HoverGroupsTutorialBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you hover over any element that is part of the group, all elements .
        /// </summary>
        internal static string HoverGroupsTutorialBody3 {
            get {
                return ResourceManager.GetString("HoverGroupsTutorialBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in it will have their hover state activated..
        /// </summary>
        internal static string HoverGroupsTutorialBody4 {
            get {
                return ResourceManager.GetString("HoverGroupsTutorialBody4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Use:.
        /// </summary>
        internal static string HoverGroupsTutorialHeader {
            get {
                return ResourceManager.GetString("HoverGroupsTutorialHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        internal static string Milliseconds {
            get {
                return ResourceManager.GetString("Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat activity timeout:.
        /// </summary>
        internal static string SettingsChatActivityTimeout {
            get {
                return ResourceManager.GetString("SettingsChatActivityTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default delay:.
        /// </summary>
        internal static string SettingsDelay {
            get {
                return ResourceManager.GetString("SettingsDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of time it takes to go back to the `Idle` column..
        /// </summary>
        internal static string SettingsDelayTooltip {
            get {
                return ResourceManager.GetString("SettingsDelayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Element.
        /// </summary>
        internal static string SettingsDisable {
            get {
                return ResourceManager.GetString("SettingsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully disables the element when the opacity of a state goes below 0.05..
        /// </summary>
        internal static string SettingsDisableTooltip {
            get {
                return ResourceManager.GetString("SettingsDisableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Configuration.
        /// </summary>
        internal static string SettingsElementConfiguration {
            get {
                return ResourceManager.GetString("SettingsElementConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotes trigger chat activity.
        /// </summary>
        internal static string SettingsEmoteActivity {
            get {
                return ResourceManager.GetString("SettingsEmoteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade In time:.
        /// </summary>
        internal static string SettingsEnterTransition {
            get {
                return ResourceManager.GetString("SettingsEnterTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in ms it takes for an element to fade in..
        /// </summary>
        internal static string SettingsEnterTransitionTooltip {
            get {
                return ResourceManager.GetString("SettingsEnterTransitionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade Out time:.
        /// </summary>
        internal static string SettingsExitTransition {
            get {
                return ResourceManager.GetString("SettingsExitTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in ms it takes for an element to fade out..
        /// </summary>
        internal static string SettingsExitTransitionTooltip {
            get {
                return ResourceManager.GetString("SettingsExitTransitionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Fade Settings.
        /// </summary>
        internal static string SettingsFadeOverride {
            get {
                return ResourceManager.GetString("SettingsFadeOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always User Focus when hotbars are unlocked.
        /// </summary>
        internal static string SettingsFocusHotbarUnlock {
            get {
                return ResourceManager.GetString("SettingsFocusHotbarUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When hotbars or crossbars are unlocked always setup to the UserFocus column..
        /// </summary>
        internal static string SettingsFocusHotbarUnlockTooltip {
            get {
                return ResourceManager.GetString("SettingsFocusHotbarUnlockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Focus key:.
        /// </summary>
        internal static string SettingsFocusKey {
            get {
                return ResourceManager.GetString("SettingsFocusKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When held interface will be setup as per &apos;UserFocus&apos; column..
        /// </summary>
        internal static string SettingsFocusKeyTooltip {
            get {
                return ResourceManager.GetString("SettingsFocusKeyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string SettingsGeneralHeader {
            get {
                return ResourceManager.GetString("SettingsGeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string SettingsHide {
            get {
                return ResourceManager.GetString("SettingsHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Opacity.
        /// </summary>
        internal static string SettingsRelativeOpacity {
            get {
                return ResourceManager.GetString("SettingsRelativeOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled, all plugin opacity values are multiplied by your native HUD-layout opacity. 
        ///This way the Plugin only operates within the bounds of your stock UI.
        ///E.g., native 60% * plugin 50% → resulting UI at 30%..
        /// </summary>
        internal static string SettingsRelativeOpacityTooltip {
            get {
                return ResourceManager.GetString("SettingsRelativeOpacityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string SettingsShow {
            get {
                return ResourceManager.GetString("SettingsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System messages trigger chat activity.
        /// </summary>
        internal static string SettingsSystemTrigger {
            get {
                return ResourceManager.GetString("SettingsSystemTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string SettingsUnknown {
            get {
                return ResourceManager.GetString("SettingsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT Key Focus.
        /// </summary>
        internal static string StateAltKey {
            get {
                return ResourceManager.GetString("StateAltKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Activity.
        /// </summary>
        internal static string StateChatActivity {
            get {
                return ResourceManager.GetString("StateChatActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Focus.
        /// </summary>
        internal static string StateChatFocus {
            get {
                return ResourceManager.GetString("StateChatFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat.
        /// </summary>
        internal static string StateCombat {
            get {
                return ResourceManager.GetString("StateCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafting.
        /// </summary>
        internal static string StateCrafting {
            get {
                return ResourceManager.GetString("StateCrafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL Key Focus.
        /// </summary>
        internal static string StateCtrlKey {
            get {
                return ResourceManager.GetString("StateCtrlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string StateDefault {
            get {
                return ResourceManager.GetString("StateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty.
        /// </summary>
        internal static string StateDuty {
            get {
                return ResourceManager.GetString("StateDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy Target.
        /// </summary>
        internal static string StateEnemyTarget {
            get {
                return ResourceManager.GetString("StateEnemyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering.
        /// </summary>
        internal static string StateGathering {
            get {
                return ResourceManager.GetString("StateGathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering Node Target.
        /// </summary>
        internal static string StateGatheringNodeTarget {
            get {
                return ResourceManager.GetString("StateGatheringNodeTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover.
        /// </summary>
        internal static string StateHover {
            get {
                return ResourceManager.GetString("StateHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Fate Area.
        /// </summary>
        internal static string StateInFateArea {
            get {
                return ResourceManager.GetString("StateInFateArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Sanctuary.
        /// </summary>
        internal static string StateInSanctuary {
            get {
                return ResourceManager.GetString("StateInSanctuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Island Sanctuary.
        /// </summary>
        internal static string StateIslandSanctuary {
            get {
                return ResourceManager.GetString("StateIslandSanctuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Moving.
        /// </summary>
        internal static string StateIsMoving {
            get {
                return ResourceManager.GetString("StateIsMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Bumper Held.
        /// </summary>
        internal static string StateLeftBumper {
            get {
                return ResourceManager.GetString("StateLeftBumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Trigger Held.
        /// </summary>
        internal static string StateLeftTrigger {
            get {
                return ResourceManager.GetString("StateLeftTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounted.
        /// </summary>
        internal static string StateMounted {
            get {
                return ResourceManager.GetString("StateMounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string StateNone {
            get {
                return ResourceManager.GetString("StateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Target.
        /// </summary>
        internal static string StateNPCTarget {
            get {
                return ResourceManager.GetString("StateNPCTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        internal static string StateOccupied {
            get {
                return ResourceManager.GetString("StateOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Target.
        /// </summary>
        internal static string StatePlayerTarget {
            get {
                return ResourceManager.GetString("StatePlayerTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Bumper Held.
        /// </summary>
        internal static string StateRightBumper {
            get {
                return ResourceManager.GetString("StateRightBumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Trigger Held.
        /// </summary>
        internal static string StateRightTrigger {
            get {
                return ResourceManager.GetString("StateRightTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIFT Key Focus.
        /// </summary>
        internal static string StateShiftKey {
            get {
                return ResourceManager.GetString("StateShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Focus.
        /// </summary>
        internal static string StateUserFocus {
            get {
                return ResourceManager.GetString("StateUserFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Disabled Elements cannot be hovered!.
        /// </summary>
        internal static string StateWarning {
            get {
                return ResourceManager.GetString("StateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Unsheathed.
        /// </summary>
        internal static string StateWeaponUnsheathed {
            get {
                return ResourceManager.GetString("StateWeaponUnsheathed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string TabAbout {
            get {
                return ResourceManager.GetString("TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover Groups.
        /// </summary>
        internal static string TabHoverGroups {
            get {
                return ResourceManager.GetString("TabHoverGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
    }
}
